language: c
# To build on OSX, switch the previous line to
# language: objective-c

script:
    - make downloaded-data-bulk-fetch downloaded-data-unpack
    - make

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - ./travis-tool.sh aptget_install libgsl0-dev
    - ./travis-tool.sh aptget_install fftw3-dev
    - ./travis-tool.sh install_deps
    - ./travis-tool.sh github_package richfitz/sowsear
    - ./travis-tool.sh github_package richfitz/diversitree
env:
  global:
    - BOOTSTRAP_LATEX="1"    
